= Compress Build Log Plugin

== About

The Compress Build Log Plugin allows configuring jobs to have their build logs compressed.
For a long time, Jenkins has supported showing gzipped build logs on the UI and through its APIs, but had no facility to compress build logs.
This plugin implements that.

== Configuring build log compression

In a job configuration, check "Compress Build Log" and save.
You're done!
From then on, when builds finish, their build log will be compressed to a `log.gz` file, after which the original `log` file will be removed.
Jenkins will transparently access the `log.gz` file when the build log is viewed or downloaded.

== Pipeline compatibility

Pipeline support was dropped from version 1.3 of the plugin, as the changes to Pipeline plugins for https://github.com/jenkinsci/jep/tree/master/jep/210[JEP-210] are incompatible with this plugin.

Earlier, version 1.2 of this plugin supported compressing full pipeline build logs.
https://plugins.jenkins.io/workflow-job[Pipeline: Job] plugin prior to version 2.26 stored per-step build logs.
This plugin did not support compressing these, only the main log file.
It could be configured either through the UI, or by adding `compressBuildLog()` to the `properties()` defined in the Pipeline DSL or Jenkinsfile.

== Issue Tracking

Issues for this plugin are tracked in the Jenkins project Jira at https://issues.jenkins-ci.org.

https://issues.jenkins-ci.org/issues/?jql=component%3Dcompress-build-log-plugin%20and%20resolution%20is%20empty[View open issues].

== Known Issues

Some plugins may assume that the build log is a text file and just append to it.
If that happens after this plugin rewrites the build log, the `log.gz` file will contain invalid contents.
Examples:

* https://issues.jenkins-ci.org/browse/JENKINS-24171[JENKINS-24171]

== Changelog

=== Upcoming Changes

* *Require Jenkins 2.150.1*
* General modernization
* Drop support for Pipelines due to JEP-210

=== Version 1.2 (2017-08-14)

* *Require Jenkins 2.7.4*
* Add support for compressing full Pipeline build logs (but not per-step logs)
* Add `+compressBuildLog()+` symbol for use in Pipeline DSL
* Add support for compressing the logs of matrix configuration builds (i.e. those doing the actual work)

=== Version 1.1 – release was skipped

=== Version 1.0 (2014-10-13)

* Initial release to address the request JENKINS-2551
